from tallyman_core import notebook
from tallyman_core.aliases import (  # noqa: I001 (keep notebook import first)
    AliasExists,
    AliasNotFound,
    alias_for_hash,
    get_alias,
    history_for,
    load_aliases,
    load_history,
    remove_alias,
    rename_alias,
    set_alias,
    validate_alias_name,
    version_of_hash,
)
from tallyman_core.charts import ChartSpecError, get_chart, list_charts, remove_chart, set_chart
from tallyman_core.config import auto_recalc_enabled, read_config, set_auto_recalc, write_config
from tallyman_core.display_klasses import (
    DisplayKlassError,
    list_display_klasses,
    remove_display_klass,
    write_display_klass,
)
from tallyman_core.entry_config import carry_forward_entry_config
from tallyman_core.errors import clear_errors, error_for_hash, errors_by_hash, get_error, list_errors, record_error
from tallyman_core.fsutil import atomic_write_text
from tallyman_core.manifest import Manifest, read_manifest, write_manifest
from tallyman_core.marimo_export import export_notebook_path, notebook_to_marimo
from tallyman_core.notebook import CellNotFound
from tallyman_core.paths import (
    ENTRY_ARTIFACT_NAMES,
    ENTRY_BUILD_DIRNAME,
    ENTRY_CACHE_NAMES,
    ENTRY_EXPANDED_BUILD_DIRNAME,
    ENTRY_MANIFEST_FILENAME,
    ENTRY_SCHEMA_FILENAME,
    ENTRY_STAT_CACHE_DIRNAME,
    artifacts_dir,
    catalog_dir,
    data_dir,
    ensure_project,
    entries_dir,
    entry_build_dir,
    entry_dir,
    entry_expanded_build_dir,
    entry_manifest_path,
    entry_schema_path,
    entry_stat_cache_dir,
    errors_path,
    exports_dir,
    list_projects,
    notebooks_dir,
    post_processing_dir,
    project_dir,
    projects_root,
    resolve_project,
    set_active_project,
    stats_dir,
    tallyman_home,
    validate_project_name,
)
from tallyman_core.post_processing import (
    PostProcessingRunError,
    PostProcessingSourceError,
    list_post_processings,
    remove_post_processing,
    run_post_processing,
    write_post_processing,
)
from tallyman_core.summary_stats import (
    StatSourceError,
    list_stats,
    remove_stat,
    write_stat,
)

__all__ = [
    "AliasExists",
    "AliasNotFound",
    "CellNotFound",
    "ChartSpecError",
    "Manifest",
    "export_notebook_path",
    "notebook_to_marimo",
    "PostProcessingRunError",
    "PostProcessingSourceError",
    "run_post_processing",
    "DisplayKlassError",
    "list_display_klasses",
    "remove_display_klass",
    "write_display_klass",
    "StatSourceError",
    "list_post_processings",
    "list_stats",
    "remove_post_processing",
    "remove_stat",
    "write_post_processing",
    "write_stat",
    "alias_for_hash",
    "atomic_write_text",
    "artifacts_dir",
    "auto_recalc_enabled",
    "catalog_dir",
    "clear_errors",
    "data_dir",
    "error_for_hash",
    "errors_by_hash",
    "read_config",
    "set_auto_recalc",
    "write_config",
    "ensure_project",
    "entries_dir",
    "entry_dir",
    "entry_build_dir",
    "entry_manifest_path",
    "entry_schema_path",
    "entry_stat_cache_dir",
    "entry_expanded_build_dir",
    "carry_forward_entry_config",
    "ENTRY_ARTIFACT_NAMES",
    "ENTRY_CACHE_NAMES",
    "ENTRY_BUILD_DIRNAME",
    "ENTRY_MANIFEST_FILENAME",
    "ENTRY_SCHEMA_FILENAME",
    "ENTRY_STAT_CACHE_DIRNAME",
    "ENTRY_EXPANDED_BUILD_DIRNAME",
    "errors_path",
    "exports_dir",
    "get_alias",
    "get_chart",
    "get_error",
    "history_for",
    "list_charts",
    "list_errors",
    "list_projects",
    "load_aliases",
    "load_history",
    "notebook",
    "notebooks_dir",
    "post_processing_dir",
    "project_dir",
    "projects_root",
    "tallyman_home",
    "read_manifest",
    "record_error",
    "remove_alias",
    "remove_chart",
    "rename_alias",
    "resolve_project",
    "set_active_project",
    "set_alias",
    "set_chart",
    "stats_dir",
    "validate_alias_name",
    "validate_project_name",
    "version_of_hash",
    "write_manifest",
]
